<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>registration</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>440fe99c-cd3e-4961-93db-501cf5e17e97</testSuiteGuid>
   <testCaseLink>
      <guid>7f44eec7-cc84-4c96-82ff-b8f2a7868ed7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Case Folder/registration/Registration Flow - Valid User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c35be0a3-41a1-49f2-84cd-0dee46414867</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b674deec-d8ab-4ff2-89c6-e3e9449cc5d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Case Folder/registration/Registration Flow - Invalid User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba00db7a-55ea-42bc-ba6f-527dd26be88d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
